services:
  mongodb:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://mongodb:27017/todo
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - blackbox-exporter
      - alertmanager

  grafana:
    image: grafana/grafana:12.1
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:
